# Generated by Django 4.1.7 on 2023-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('FlowId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DecimalField(decimal_places=0, max_digits=50)),
                ('value', models.DecimalField(decimal_places=45, max_digits=50)),
            ],
        ),
    ]
