# Generated by Django 4.1.7 on 2023-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('ParamName', models.TextField()),
                ('ParamDescription', models.TextField()),
                ('ParamType', models.TextField()),
                ('ParamStartRange', models.TextField()),
                ('ParamEndRange', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usertype', models.CharField(choices=[('1', 'user'), ('2', 'admin')], default='1', max_length=32)),
            ],
        ),
    ]
