# Generated by Django 4.1.7 on 2023-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('UserEmailId', models.AutoField(primary_key=True, serialize=False)),
                ('EmailAddress', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
