# Generated by Django 4.1.7 on 2023-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('UserPhoneId', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
